/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4a4333de-2e73-4d8a-9292-eb2fe5ff6c80",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NccOpWCLI",
    "aws_user_pools_web_client_id": "43qaobu0ue1u1rjm7jlhu8t6qi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://g7pgdyjtobhhtphh4ljszfexnq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2ymi3v5txzakrnuue3jujwpgom"
};


export default awsmobile;
